# On plugin update, please save the changes to the file, delete it and then change the values again.

Enabled: true
Combat time: 15
Banning commands: true
Banning teleport: false
Banning exiting: false
Commands: "&c===================\n\n&bCommands available:\n  &a/combatnap toggle <on/off>\n  &a/combatnap reload\n\n&c==================="
Plugin enabled: "&b[CombatNap] &7The plugin has been &aenabled&7!"
Plugin already enabled: "&b[CombatNap] &7The plugin is already &aenabled&7!"
Plugin disabled: "&b[CombatNap] &7The plugin has been &cdisabled&7!"
Plugin already disabled: "&b[CombatNap] &7The plugin is already &cdisabled&7!"
Invalid toggle: "&b[CombatNap] &7Invalid use of command. Please use &c/combatnap toggle <on/off>&7!"
Banned commands:
  - spawn
  - back
  - tp